# Local In-Memory Database Setup
server.port=8081
app.cors.allowed-origins=http://localhost:3000
# 1. Secure Database Connection using Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Resilient Cloud Redis Configurations (Securely Hidden)
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.ssl=false
spring.redis.password=${REDIS_PASSWORD}

UPSTASH_REDIS_REST_URL="https://hot-trout-136037.upstash.io"
# Safely pull the token from your computer's local system environment variables
UPSTASH_REDIS_REST_TOKEN=${MY_REDIS_SECRET_TOKEN}
spring.redis.timeout=5000ms
spring.redis.connect-timeout=5000ms

# 2. Hibernate Schema Management
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Enable H2 Web Console so you can see your tables in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console






